# Introduction into Pandas

## Part 1: Creating a Pandas DataFrame
Can be from a List, Dictionary or List of Dictionaries

In [13]:
# We first import pandas
import pandas as pd

# using a list
proudly_sa = [
    "Galxboy",
    "Bathu",
    "Drip",
    "Maxhosa",
    "Tshepo Jeans"
]

# proudly_sa
proudly_sa

['Galxboy', 'Bathu', 'Drip', 'Maxhosa', 'Tshepo Jeans']

In [14]:
# Now from a dictionary

import pandas as pd

# Define a dictionary

proudly_sa_dict = {
    'Brand': ['Galxboy', 'Bathu', 'Drip', 'Maxhosa', 'Tshepo Jeans'],
    'Year Founded': [2010, 2015, 2019, 2012, 2015],
    'Speciality': ['Streetwear/Fashion', 'Sneakers', 'Sneakers/Lifestyle', 'Luxury Knitwear', 'Premium Denim'],
    'Founder': ['Thatiso Dube', 'Theo Baloyi', 'Lekau Sehoana', 'Laduma Ngxokolo', 'Tshepo Mohlala']
}

# proudly_sa_dict

# Create a DataFrame from a dictionary

dict_df = pd.DataFrame(proudly_sa_dict)

dict_df

          Brand  Year Founded          Speciality          Founder
0       Galxboy          2010  Streetwear/Fashion     Thatiso Dube
1         Bathu          2015            Sneakers      Theo Baloyi
2          Drip          2019  Sneakers/Lifestyle    Lekau Sehoana
3       Maxhosa          2012     Luxury Knitwear  Laduma Ngxokolo
4  Tshepo Jeans          2015       Premium Denim   Tshepo Mohlala

In [15]:
# Querying a DataFrame column

founders = dict_df['Founder']

founders

0       Thatiso Dube
1        Theo Baloyi
2      Lekau Sehoana
3    Laduma Ngxokolo
4     Tshepo Mohlala
Name: Founder, dtype: object

In [16]:
# Querying a specific value
drip_owner = dict_df.loc[2, 'Founder']
drip_owner

'Lekau Sehoana'

# Part 2: DataFrames from External Sources
Excel, CSVs and More...

## 2.1 CSV to DataFrame
#### Upload from Google Drive Mount

In [17]:
# imports
import pandas as pd

# specify the file path
file_path = 'sa_loan_eligibility_data.csv'

# Read the CSV file into a DataFrame
df = pd.read_csv(file_path)

df.head() # show the first 5 rows

# df.tail() # last 5 rows

,Full_Name,Province,Age,Income,Employment_Status,Credit_Score,Home_Owner,Has_Debt,Loan_Approved
0,Ayanda Van Wyk,Eastern Cape,61,16127,Unemployed,407,Yes,No,No
1,Thabo Mahlangu,North West,21,20091,Self-employed,690,No,Yes,No
2,Sipho Naidoo,KwaZulu-Natal,29,64532,Self-employed,343,No,No,No
3,Lerato Mokoena,Mpumalanga,43,49062,Employed,645,No,No,Yes
4,Thabo Dlamini,KwaZulu-Natal,25,6120,Unemployed,434,Yes,No,No

## 2.2 Excel to DataFrame
#### Upload from Google Drive Mount

In [18]:
# Imports
import pandas as pd

# Path to file
file_path = 'many_sheets_data.xlsx'

# Read the Excel file into a DataFrame
df = pd.read_excel(file_path)

df.head()

,Full_Name,Province,Age,Income,Employment_Status,Credit_Score,Home_Owner,Has_Debt,Loan_Approved
0,Ayanda Van Wyk,Eastern Cape,61,16127,Unemployed,407,Yes,No,No
1,Thabo Mahlangu,North West,21,20091,Self-employed,690,No,Yes,No
2,Sipho Naidoo,KwaZulu-Natal,29,64532,Self-employed,343,No,No,No
3,Lerato Mokoena,Mpumalanga,43,49062,Employed,645,No,No,Yes
4,Thabo Dlamini,KwaZulu-Natal,25,6120,Unemployed,434,Yes,No,No

# Part 3: Dealing with Malformed data
* Sheets don't have headers​
* There are more than one sheet in the Excel File​
* Sheets don't have headers​
* Headers exists, but we would like to rename them to fit
our narrative.


---

##### 3.1 No headers


---

In [20]:
# imports
import pandas as pd

# get the file path
file_path = 'no_headers.xlsx'

# Read the Excel file into a DataFrame
df = pd.read_excel(file_path)

df.head()

   Ayanda Van Wyk   Eastern Cape  61  16127     Unemployed  407  Yes   No No.1
0  Thabo Mahlangu     North West  21  20091  Self-employed  690   No  Yes   No
1    Sipho Naidoo  KwaZulu-Natal  29  64532  Self-employed  343   No   No   No
2  Lerato Mokoena     Mpumalanga  43  49062       Employed  645   No   No  Yes
3   Thabo Dlamini  KwaZulu-Natal  25   6120     Unemployed  434  Yes   No   No
4  Kabelo Ngubane  KwaZulu-Natal  32  65690  Self-employed  529   No   No   No

In [21]:
# You can specify to pandas that there are no headers:
df = pd.read_excel(file_path, header=None)

# It then defaults to numbering the columns
df.head()

                0              1   2      3              4    5    6    7    8
0  Ayanda Van Wyk   Eastern Cape  61  16127     Unemployed  407  Yes   No   No
1  Thabo Mahlangu     North West  21  20091  Self-employed  690   No  Yes   No
2    Sipho Naidoo  KwaZulu-Natal  29  64532  Self-employed  343   No   No   No
3  Lerato Mokoena     Mpumalanga  43  49062       Employed  645   No   No  Yes
4   Thabo Dlamini  KwaZulu-Natal  25   6120     Unemployed  434  Yes   No   No

In [22]:
# You can then create your 'own' headers
# specify your header names
column_names = ['Full_Name', 'Province', 'Age', 'Income', 'Employment_Status',
                'Credit_Score', 'Home_Owner', 'Has_Debt', 'Loan_Approved']

df = pd.read_excel(file_path, header=None, names=column_names)

df.head()

,Full_Name,Province,Age,Income,Employment_Status,Credit_Score,Home_Owner,Has_Debt,Loan_Approved
0,Ayanda Van Wyk,Eastern Cape,61,16127,Unemployed,407,Yes,No,No
1,Thabo Mahlangu,North West,21,20091,Self-employed,690,No,Yes,No
2,Sipho Naidoo,KwaZulu-Natal,29,64532,Self-employed,343,No,No,No
3,Lerato Mokoena,Mpumalanga,43,49062,Employed,645,No,No,Yes
4,Thabo Dlamini,KwaZulu-Natal,25,6120,Unemployed,434,Yes,No,No

##### 3.2 More than one sheet in Excel


---

In [24]:
# import pandas
import pandas as pd

# Get the file path
file_path = 'many_sheets_data.xlsx'

# Read the Excel file into a DataFrame
df = pd.read_excel(file_path)

# It only brings out the first sheet
df.head()

,Full_Name,Province,Age,Income,Employment_Status,Credit_Score,Home_Owner,Has_Debt,Loan_Approved
0,Ayanda Van Wyk,Eastern Cape,61,16127,Unemployed,407,Yes,No,No
1,Thabo Mahlangu,North West,21,20091,Self-employed,690,No,Yes,No
2,Sipho Naidoo,KwaZulu-Natal,29,64532,Self-employed,343,No,No,No
3,Lerato Mokoena,Mpumalanga,43,49062,Employed,645,No,No,Yes
4,Thabo Dlamini,KwaZulu-Natal,25,6120,Unemployed,434,Yes,No,No

In [25]:
# To get a specific sheet. You specify the sheet name
df_soccer = pd.read_excel(file_path, sheet_name='soccer_probability')
df_soccer.head()

,Team Name,League,Opponent,Location,Match Condition,Goals Last 3,Win Probability
0,SuperSport United,PSL,Casric Stars,Away,Derby,5,0.34
1,Orlando Pirates,PSL,University of Pretoria,Away,Windy,6,0.58
2,Cape Town Spurs,PSL,Orlando Pirates,Away,Night Match,5,0.71
3,Baroka FC,NFD,Venda FC,Away,Windy,0,0.48
4,Orlando Pirates,PSL,Zizwe United,Away,Night Match,3,0.66

### 3.3 Information at the Top of the Excel Table


---

In [27]:
# imports
import pandas as pd

# File Path
file_path = 'comments_sa_matches.xlsx'

# Read the Excel file into a DataFrame
df = pd.read_excel(file_path)
df.head()

,"The Premier Soccer League (PSL) is the administrative body for professional soccer leagues and cups in South Africa. It is based in Johannesburg, and was founded in 1996 following an agreement between the National Soccer League and the remnants of the National Professional Soccer League (NPSL).",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Affiliated to the South African Football Assoc...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Organisation,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
# To get the correct info, skip the rows that don't include the real data
df = pd.read_excel(file_path, skiprows=3)
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Organisation,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,The Premier Soccer League sell the naming righ...,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"They had previously organized the Charity Cup,...",NaN,NaN,NaN,NaN,NaN,NaN

### 3.4 Renaming Headers


---

In [30]:
# Import
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('sa_loan_eligibility_data.csv')
df.head()

,Full_Name,Province,Age,Income,Employment_Status,Credit_Score,Home_Owner,Has_Debt,Loan_Approved
0,Ayanda Van Wyk,Eastern Cape,61,16127,Unemployed,407,Yes,No,No
1,Thabo Mahlangu,North West,21,20091,Self-employed,690,No,Yes,No
2,Sipho Naidoo,KwaZulu-Natal,29,64532,Self-employed,343,No,No,No
3,Lerato Mokoena,Mpumalanga,43,49062,Employed,645,No,No,Yes
4,Thabo Dlamini,KwaZulu-Natal,25,6120,Unemployed,434,Yes,No,No

In [31]:
# What if we wanted to rename 'Income' to 'Monthly Income'
df = df.rename(columns={'Income': 'Monthly Income'})
df.head()

,Full_Name,Province,Age,Monthly Income,Employment_Status,Credit_Score,Home_Owner,Has_Debt,Loan_Approved
0,Ayanda Van Wyk,Eastern Cape,61,16127,Unemployed,407,Yes,No,No
1,Thabo Mahlangu,North West,21,20091,Self-employed,690,No,Yes,No
2,Sipho Naidoo,KwaZulu-Natal,29,64532,Self-employed,343,No,No,No
3,Lerato Mokoena,Mpumalanga,43,49062,Employed,645,No,No,Yes
4,Thabo Dlamini,KwaZulu-Natal,25,6120,Unemployed,434,Yes,No,No

# Part 4: Exporting Data


---
After processing, data often needs to be exported for further use



---

### 4.1 DataFrame to CSV
`df.to_csv('path/to/file.csv')`

In [32]:
# Let us pretent the dictionary is from some process...

# Define a dictionary
processed_data = {
    'Team Name': ['Dondol Stars', 'Orlando Pirates', 'Bush Bucks'],
    'League': ['ABC Motsepe', 'PSL', 'NFD'],
    'Win Probability': [0.53, 0.58, 0.66]
}

# Create a dataframe from a dictionary
df = pd.DataFrame(processed_data)
df

         Team Name       League  Win Probability
0     Dondol Stars  ABC Motsepe             0.53
1  Orlando Pirates          PSL             0.58
2       Bush Bucks          NFD             0.66

In [34]:
# Now let us write to a csv file

# first let us specify the file path
output_path = 'processed_matches.csv'

# write to a csv
df.to_csv(output_path, index=False)

### 4.2 DataFrame to Excel
`df.to_excel('path/to/file.csv')`

In [36]:
# Now let us write to a excel file

# first let us specify the file path
output_path = 'processed_matches.xlsx'

# write to a excel
df.to_excel(output_path, index=False)

# Part 5: Modifying DataFrames


---

### 5.1 Replacing

In [37]:
# imports
import pandas as pd
import numpy as np

# Read the Excel file into a DataFrame
df = pd.read_excel('dirty_detailed.xlsx')
df.head(10)

,Team Name,League,Opponent,Location,Match Condition,Goals Last 3,Attendance,Temperature (°C),Team Possession (%),Shots on Target,Yellow Cards,Win Probability
0,Dondol Stars,ABC Motsepe,Santos FC,--,Night Match,1,32752,11.1,60.8,1,0,0.53
1,Mpheni Home Defenders,PSL,Orbit College,--,Derby,1,17255,34.4,48.9,0,4,0.5
2,Black Leopards,NFD,Venda FC,Away,Night Match,1,--,--,59.8,8,5,0.83
3,--,ABC Motsepe,Cape Town Spurs,Home,Derby,6,39233,17.8,44.3,7,--,0.34
4,--,PSL,Polokwane City,Away,Sunny,4,26120,33.9,65.2,1,2,0.37
5,Bush Bucks,NFD,Upington City,Home,Sunny,0,28727,--,40.8,3,3,0.62
6,Magesi FC,ABC Motsepe,Polokwane City,Away,Sunny,1,--,23,45.3,--,1,0.54
7,Santos FC,PSL,Black Leopards,Home,Night Match,5,36861,33,50.2,5,1,0.46
8,Cape Town Spurs,NFD,SuperSport United,Away,Windy,5,47177,27.3,68.1,3,2,--
9,Zizwe United,ABC Motsepe,Mangaung Unite,Home,Windy,0,--,15.1,43.5,6,0,0.82

In [38]:
# Let us replace -- on numbered columns with nan
numeric_cols = ['Attendance', 'Temperature (°C)', 'Shots on Target', 'Yellow Cards', 'Win Probability']
df[numeric_cols] = df[numeric_cols].replace('--', np.nan)
df

/tmp/ipykernel_1397/3242384322.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[numeric_cols] = df[numeric_cols].replace('--', np.nan)

,Team Name,League,Opponent,Location,Match Condition,Goals Last 3,Attendance,Temperature (°C),Team Possession (%),Shots on Target,Yellow Cards,Win Probability
0,Dondol Stars,ABC Motsepe,Santos FC,--,Night Match,1,32752.0,11.1,60.8,1.0,0.0,0.53
1,Mpheni Home Defenders,PSL,Orbit College,--,Derby,1,17255.0,34.4,48.9,0.0,4.0,0.50
2,Black Leopards,NFD,Venda FC,Away,Night Match,1,NaN,NaN,59.8,8.0,5.0,0.83
3,--,ABC Motsepe,Cape Town Spurs,Home,Derby,6,39233.0,17.8,44.3,7.0,NaN,0.34
4,--,PSL,Polokwane City,Away,Sunny,4,26120.0,33.9,65.2,1.0,2.0,0.37
5,Bush Bucks,NFD,Upington City,Home,Sunny,0,28727.0,NaN,40.8,3.0,3.0,0.62
6,Magesi FC,ABC Motsepe,Polokwane City,Away,Sunny,1,NaN,23.0,45.3,NaN,1.0,0.54
7,Santos FC,PSL,Black Leopards,Home,Night Match,5,36861.0,33.0,50.2,5.0,1.0,0.46
8,Cape Town Spurs,NFD,SuperSport United,Away,Windy,5,47177.0,27.3,68.1,3.0,2.0,NaN
9,Zizwe United,ABC Motsepe,Mangaung Unite,Home,Windy,0,NaN,15.1,43.5,6.0,0.0,0.82

In [39]:
# Replacing in specific columns.
df['Win Probability'] = df['Win Probability'].replace('--', np.nan)
df

,Team Name,League,Opponent,Location,Match Condition,Goals Last 3,Attendance,Temperature (°C),Team Possession (%),Shots on Target,Yellow Cards,Win Probability
0,Dondol Stars,ABC Motsepe,Santos FC,--,Night Match,1,32752.0,11.1,60.8,1.0,0.0,0.53
1,Mpheni Home Defenders,PSL,Orbit College,--,Derby,1,17255.0,34.4,48.9,0.0,4.0,0.50
2,Black Leopards,NFD,Venda FC,Away,Night Match,1,NaN,NaN,59.8,8.0,5.0,0.83
3,--,ABC Motsepe,Cape Town Spurs,Home,Derby,6,39233.0,17.8,44.3,7.0,NaN,0.34
4,--,PSL,Polokwane City,Away,Sunny,4,26120.0,33.9,65.2,1.0,2.0,0.37
5,Bush Bucks,NFD,Upington City,Home,Sunny,0,28727.0,NaN,40.8,3.0,3.0,0.62
6,Magesi FC,ABC Motsepe,Polokwane City,Away,Sunny,1,NaN,23.0,45.3,NaN,1.0,0.54
7,Santos FC,PSL,Black Leopards,Home,Night Match,5,36861.0,33.0,50.2,5.0,1.0,0.46
8,Cape Town Spurs,NFD,SuperSport United,Away,Windy,5,47177.0,27.3,68.1,3.0,2.0,NaN
9,Zizwe United,ABC Motsepe,Mangaung Unite,Home,Windy,0,NaN,15.1,43.5,6.0,0.0,0.82

### 5.2 Removing

In [40]:
# imports
import pandas as pd

# Read the Excel file into a DataFrame
df = pd.read_excel('dirty_detailed.xlsx')
df

,Team Name,League,Opponent,Location,Match Condition,Goals Last 3,Attendance,Temperature (°C),Team Possession (%),Shots on Target,Yellow Cards,Win Probability
0,Dondol Stars,ABC Motsepe,Santos FC,--,Night Match,1,32752,11.1,60.8,1,0,0.53
1,Mpheni Home Defenders,PSL,Orbit College,--,Derby,1,17255,34.4,48.9,0,4,0.5
2,Black Leopards,NFD,Venda FC,Away,Night Match,1,--,--,59.8,8,5,0.83
3,--,ABC Motsepe,Cape Town Spurs,Home,Derby,6,39233,17.8,44.3,7,--,0.34
4,--,PSL,Polokwane City,Away,Sunny,4,26120,33.9,65.2,1,2,0.37
5,Bush Bucks,NFD,Upington City,Home,Sunny,0,28727,--,40.8,3,3,0.62
6,Magesi FC,ABC Motsepe,Polokwane City,Away,Sunny,1,--,23,45.3,--,1,0.54
7,Santos FC,PSL,Black Leopards,Home,Night Match,5,36861,33,50.2,5,1,0.46
8,Cape Town Spurs,NFD,SuperSport United,Away,Windy,5,47177,27.3,68.1,3,2,--
9,Zizwe United,ABC Motsepe,Mangaung Unite,Home,Windy,0,--,15.1,43.5,6,0,0.82

In [41]:
# We want to replace rows with Team names  as --
df['Team Name'] != '--'

0     True
1     True
2     True
3    False
4    False
5     True
6     True
7     True
8     True
9     True
Name: Team Name, dtype: bool

In [42]:
# If we include the original dataframe, we will only get instances where the result is true
df = df[df['Team Name'] != '--']
df

,Team Name,League,Opponent,Location,Match Condition,Goals Last 3,Attendance,Temperature (°C),Team Possession (%),Shots on Target,Yellow Cards,Win Probability
0,Dondol Stars,ABC Motsepe,Santos FC,--,Night Match,1,32752,11.1,60.8,1,0,0.53
1,Mpheni Home Defenders,PSL,Orbit College,--,Derby,1,17255,34.4,48.9,0,4,0.5
2,Black Leopards,NFD,Venda FC,Away,Night Match,1,--,--,59.8,8,5,0.83
5,Bush Bucks,NFD,Upington City,Home,Sunny,0,28727,--,40.8,3,3,0.62
6,Magesi FC,ABC Motsepe,Polokwane City,Away,Sunny,1,--,23,45.3,--,1,0.54
7,Santos FC,PSL,Black Leopards,Home,Night Match,5,36861,33,50.2,5,1,0.46
8,Cape Town Spurs,NFD,SuperSport United,Away,Windy,5,47177,27.3,68.1,3,2,--
9,Zizwe United,ABC Motsepe,Mangaung Unite,Home,Windy,0,--,15.1,43.5,6,0,0.82

In [43]:
# We the need to reset the index
df = df.reset_index()
df

,index,Team Name,League,Opponent,Location,Match Condition,Goals Last 3,Attendance,Temperature (°C),Team Possession (%),Shots on Target,Yellow Cards,Win Probability
0,0,Dondol Stars,ABC Motsepe,Santos FC,--,Night Match,1,32752,11.1,60.8,1,0,0.53
1,1,Mpheni Home Defenders,PSL,Orbit College,--,Derby,1,17255,34.4,48.9,0,4,0.5
2,2,Black Leopards,NFD,Venda FC,Away,Night Match,1,--,--,59.8,8,5,0.83
3,5,Bush Bucks,NFD,Upington City,Home,Sunny,0,28727,--,40.8,3,3,0.62
4,6,Magesi FC,ABC Motsepe,Polokwane City,Away,Sunny,1,--,23,45.3,--,1,0.54
5,7,Santos FC,PSL,Black Leopards,Home,Night Match,5,36861,33,50.2,5,1,0.46
6,8,Cape Town Spurs,NFD,SuperSport United,Away,Windy,5,47177,27.3,68.1,3,2,--
7,9,Zizwe United,ABC Motsepe,Mangaung Unite,Home,Windy,0,--,15.1,43.5,6,0,0.82

### Now let us move to removing columns

In [44]:
# We want to remove League and index
# Using Drop
df = df.drop(columns=['League', 'index'])
df

,Team Name,Opponent,Location,Match Condition,Goals Last 3,Attendance,Temperature (°C),Team Possession (%),Shots on Target,Yellow Cards,Win Probability
0,Dondol Stars,Santos FC,--,Night Match,1,32752,11.1,60.8,1,0,0.53
1,Mpheni Home Defenders,Orbit College,--,Derby,1,17255,34.4,48.9,0,4,0.5
2,Black Leopards,Venda FC,Away,Night Match,1,--,--,59.8,8,5,0.83
3,Bush Bucks,Upington City,Home,Sunny,0,28727,--,40.8,3,3,0.62
4,Magesi FC,Polokwane City,Away,Sunny,1,--,23,45.3,--,1,0.54
5,Santos FC,Black Leopards,Home,Night Match,5,36861,33,50.2,5,1,0.46
6,Cape Town Spurs,SuperSport United,Away,Windy,5,47177,27.3,68.1,3,2,--
7,Zizwe United,Mangaung Unite,Home,Windy,0,--,15.1,43.5,6,0,0.82

In [45]:
# We want to keep only Team Name, Opponent and Win Probability
# Using Filter
# axis=1 for colunms
df_filtered = df.filter(items=['Team Name', 'Opponent', 'Win Probability'], axis=1)
df_filtered

               Team Name           Opponent Win Probability
0           Dondol Stars          Santos FC            0.53
1  Mpheni Home Defenders      Orbit College             0.5
2         Black Leopards           Venda FC            0.83
3             Bush Bucks      Upington City            0.62
4              Magesi FC     Polokwane City            0.54
5              Santos FC     Black Leopards            0.46
6        Cape Town Spurs  SuperSport United              --
7           Zizwe United     Mangaung Unite            0.82

#### 5.3 Dropping Duplicates

In [47]:
import pandas as pd

# Read the file into a DataFrame (duplicates sheet)
df = pd.read_excel('dirty_data.xlsx', sheet_name='duplicates')
df

,Team Name,Competition,Opponent,Location,Match Condition,Goals Last 3,Attendance,Temperature (°C),Team Possession (%),Shots on Target,Yellow Cards,Win Probability
0,Dondol Stars,ABC Motsepe,Santos FC,Home,Night Match,1,32752,11.1,60.8,1,0,0.53
1,Dondol Stars,ABC Motsepe,Santos FC,Home,Night Match,1,32752,11.1,60.8,1,0,0.53
2,Mpheni Home Defenders,PSL,Orbit College,Home,Derby,1,17255,34.4,48.9,0,4,0.5
3,Mpheni Home Defenders,PSL,Orbit College,Home,Derby,1,17255,34.4,48.9,0,4,0.5
4,Black Leopards,NFD,Venda FC,Away,Night Match,1,--,--,59.8,8,5,0.83
...,...,...,...,...,...,...,...,...,...,...,...,...
85,Steenberg Utd,PSL,Stellenbosch FC,Away,Night Match,1,18765,33.4,59.1,2,3,0.67
86,FC Cape Town,NFD,CT All Stars,Home,Derby,4,23456,48.3,67.8,6,1,1.89
87,Milford FC,ABC Motsepe,Maccabi FC,Away,Sunny,0,5432,29.8,52.4,0,4,0.23
88,AmaZulu,PSL,Golden Arrows,Home,Rainy,2,32109,43.6,65.7,5,3,1.56
89,Pretoria Callies,NFD,Uthongathi FC,Home,Windy,1,7654,37.2,57.3,2,2,0.59

In [48]:
# Removing Duplicates
# Have an option of completely dropping by setting keep = False
# You can keep the last entry by specifyin keep = 'last'
df_no_dups = df.drop_duplicates()
df_no_dups

,Team Name,Competition,Opponent,Location,Match Condition,Goals Last 3,Attendance,Temperature (°C),Team Possession (%),Shots on Target,Yellow Cards,Win Probability
0,Dondol Stars,ABC Motsepe,Santos FC,Home,Night Match,1,32752,11.1,60.8,1,0,0.53
2,Mpheni Home Defenders,PSL,Orbit College,Home,Derby,1,17255,34.4,48.9,0,4,0.5
4,Black Leopards,NFD,Venda FC,Away,Night Match,1,--,--,59.8,8,5,0.83
6,Kaizer Chiefs,ABC Motsepe,Cape Town Spurs,Home,Derby,6,39233,17.8,44.3,7,--,0.34
8,Kaizer Chiefs,PSL,Polokwane City,Away,Sunny,4,26120,33.9,65.2,1,2,0.37
10,Bush Bucks,NFD,Upington City,Home,Sunny,0,28727,--,40.8,3,3,0.62
12,Magesi FC,ABC Motsepe,Polokwane City,Away,Sunny,1,--,23,45.3,--,1,0.54
14,Santos FC,PSL,Black Leopards,Home,Night Match,5,36861,33,50.2,5,1,0.46
16,Cape Town Spurs,NFD,SuperSport United,Away,Windy,5,47177,27.3,68.1,3,2,--
18,Zizwe United,ABC Motsepe,Mangaung Unite,Home,Windy,0,--,15.1,43.5,6,0,0.82
20,Hungry Lions,NFD,TS Galaxy,Home,Rainy,2,15432,42.5,61.2,4,2,1.12
21,JDR Stars,ABC Motsepe,University of Pretoria,Away,Sunny,1,8765,38.7,55.4,2,3,0.78
22,Royal AM,PSL,Kaizer Chiefs,Home,Night Match,3,42189,45.1,72.3,7,4,2.34
23,Maritzburg United,NFD,Richards Bay,Home,Windy,0,12345,36.8,58.9,1,5,0.45
24,Tshakhuma FC,ABC Motsepe,Baroka FC,Home,Sunny,2,9876,41.2,63.7,3,2,1.05
25,Steenberg Utd,PSL,Stellenbosch FC,Away,Night Match,1,18765,33.4,59.1,2,3,0.67
26,FC Cape Town,NFD,CT All Stars,Home,Derby,4,23456,48.3,67.8,6,1,1.89
27,Milford FC,ABC Motsepe,Maccabi FC,Away,Sunny,0,5432,29.8,52.4,0,4,0.23
28,AmaZulu,PSL,Golden Arrows,Home,Rainy,2,32109,43.6,65.7,5,3,1.56
29,Pretoria Callies,NFD,Uthongathi FC,Home,Windy,1,7654,37.2,57.3,2,2,0.59

In [49]:
# Reset the index
df_no_dups = df_no_dups.reset_index(drop=True)
df_no_dups

,Team Name,Competition,Opponent,Location,Match Condition,Goals Last 3,Attendance,Temperature (°C),Team Possession (%),Shots on Target,Yellow Cards,Win Probability
0,Dondol Stars,ABC Motsepe,Santos FC,Home,Night Match,1,32752,11.1,60.8,1,0,0.53
1,Mpheni Home Defenders,PSL,Orbit College,Home,Derby,1,17255,34.4,48.9,0,4,0.5
2,Black Leopards,NFD,Venda FC,Away,Night Match,1,--,--,59.8,8,5,0.83
3,Kaizer Chiefs,ABC Motsepe,Cape Town Spurs,Home,Derby,6,39233,17.8,44.3,7,--,0.34
4,Kaizer Chiefs,PSL,Polokwane City,Away,Sunny,4,26120,33.9,65.2,1,2,0.37
5,Bush Bucks,NFD,Upington City,Home,Sunny,0,28727,--,40.8,3,3,0.62
6,Magesi FC,ABC Motsepe,Polokwane City,Away,Sunny,1,--,23,45.3,--,1,0.54
7,Santos FC,PSL,Black Leopards,Home,Night Match,5,36861,33,50.2,5,1,0.46
8,Cape Town Spurs,NFD,SuperSport United,Away,Windy,5,47177,27.3,68.1,3,2,--
9,Zizwe United,ABC Motsepe,Mangaung Unite,Home,Windy,0,--,15.1,43.5,6,0,0.82
10,Hungry Lions,NFD,TS Galaxy,Home,Rainy,2,15432,42.5,61.2,4,2,1.12
11,JDR Stars,ABC Motsepe,University of Pretoria,Away,Sunny,1,8765,38.7,55.4,2,3,0.78
12,Royal AM,PSL,Kaizer Chiefs,Home,Night Match,3,42189,45.1,72.3,7,4,2.34
13,Maritzburg United,NFD,Richards Bay,Home,Windy,0,12345,36.8,58.9,1,5,0.45
14,Tshakhuma FC,ABC Motsepe,Baroka FC,Home,Sunny,2,9876,41.2,63.7,3,2,1.05
15,Steenberg Utd,PSL,Stellenbosch FC,Away,Night Match,1,18765,33.4,59.1,2,3,0.67
16,FC Cape Town,NFD,CT All Stars,Home,Derby,4,23456,48.3,67.8,6,1,1.89
17,Milford FC,ABC Motsepe,Maccabi FC,Away,Sunny,0,5432,29.8,52.4,0,4,0.23
18,AmaZulu,PSL,Golden Arrows,Home,Rainy,2,32109,43.6,65.7,5,3,1.56
19,Pretoria Callies,NFD,Uthongathi FC,Home,Windy,1,7654,37.2,57.3,2,2,0.59

# Part 6: Dates


---

### 6.1 Date as a string

In [58]:
#1. Changing type to date

# imports
import pandas as pd

# Read the Excel file into a DataFrame
df = pd.read_csv('matches_with_dates.csv')
df

,Team Name,League,Opponent,Location,Match Condition,Goals Last 3,Win Probability,Match Date,Year,Month,Day
0,SuperSport United,PSL,Casric Stars,Away,Derby,5,0.34,2026-03-01,2026,3,1
1,Orlando Pirates,PSL,University of Pretoria,Away,Windy,6,0.58,2026-03-02,2026,3,2
2,Cape Town Spurs,PSL,Orlando Pirates,Away,Night Match,5,0.71,2026-03-03,2026,3,3
3,Baroka FC,NFD,Venda FC,Away,Windy,0,0.48,2026-03-04,2026,3,4
4,Orlando Pirates,PSL,Zizwe United,Away,Night Match,3,0.66,2026-03-05,2026,3,5
5,Richards Bay,PSL,Umvoti FC,Home,Rainy,0,0.40,2026-03-06,2026,3,6
6,Orbit College,ABC Motsepe,Pretoria Callies,Home,Derby,1,0.67,2026-03-07,2026,3,7
7,Sekhukhune United,PSL,Platinum City Rovers,Home,Rainy,6,0.46,2026-03-08,2026,3,8
8,Platinum City Rovers,NFD,Santos FC,Away,Night Match,6,0.42,2026-03-09,2026,3,9
9,Mamelodi Sundowns,PSL,Royal AM,Away,Rainy,1,0.70,2026-03-10,2026,3,10

check the type

In [59]:
# Let us check the type of Match Date
df.dtypes

Team Name           object
League              object
Opponent            object
Location            object
Match Condition     object
Goals Last 3         int64
Win Probability    float64
Match Date          object
Year                 int64
Month                int64
Day                  int64
dtype: object

Change to datetime

In [60]:
# Change the string date to type datetime
df['Match Date'] = pd.to_datetime(df['Match Date'])
df

,Team Name,League,Opponent,Location,Match Condition,Goals Last 3,Win Probability,Match Date,Year,Month,Day
0,SuperSport United,PSL,Casric Stars,Away,Derby,5,0.34,2026-03-01,2026,3,1
1,Orlando Pirates,PSL,University of Pretoria,Away,Windy,6,0.58,2026-03-02,2026,3,2
2,Cape Town Spurs,PSL,Orlando Pirates,Away,Night Match,5,0.71,2026-03-03,2026,3,3
3,Baroka FC,NFD,Venda FC,Away,Windy,0,0.48,2026-03-04,2026,3,4
4,Orlando Pirates,PSL,Zizwe United,Away,Night Match,3,0.66,2026-03-05,2026,3,5
5,Richards Bay,PSL,Umvoti FC,Home,Rainy,0,0.40,2026-03-06,2026,3,6
6,Orbit College,ABC Motsepe,Pretoria Callies,Home,Derby,1,0.67,2026-03-07,2026,3,7
7,Sekhukhune United,PSL,Platinum City Rovers,Home,Rainy,6,0.46,2026-03-08,2026,3,8
8,Platinum City Rovers,NFD,Santos FC,Away,Night Match,6,0.42,2026-03-09,2026,3,9
9,Mamelodi Sundowns,PSL,Royal AM,Away,Rainy,1,0.70,2026-03-10,2026,3,10

In [61]:
# Let us check the type again
df.dtypes

Team Name                  object
League                     object
Opponent                   object
Location                   object
Match Condition            object
Goals Last 3                int64
Win Probability           float64
Match Date         datetime64[ns]
Year                        int64
Month                       int64
Day                         int64
dtype: object

### 6.2 Date, Month and Day in Different Columns

In [65]:
# imports
import pandas as pd

# Read the Excel file into a DataFrame
df = pd.read_csv('matches_split_dates.csv')
df

,Team Name,League,Opponent,Location,Match Condition,Goals Last 3,Win Probability,Year,Month,Day
0,University of Pretoria,NFD,Bush Bucks,Away,Derby,6,0.86,2026,4,1
1,Richards Bay,PSL,Baroka FC,Home,Windy,3,0.69,2026,4,2
2,Magesi FC,NFD,Mangaung United,Away,Windy,6,0.32,2026,4,3
3,Mpheni Home Defenders,ABC Motsepe,Santos FC,Home,Night Match,4,0.35,2026,4,4
4,Sekhukhune United,PSL,Baroka FC,Away,Night Match,6,0.71,2026,4,5
5,Dondol Stars,ABC Motsepe,Casric Stars,Home,Derby,0,0.44,2026,4,6
6,Upington City,NFD,Sekhukhune United,Home,Windy,4,0.49,2026,4,7
7,Zizwe United,ABC Motsepe,Santos FC,Away,Rainy,2,0.37,2026,4,8
8,Dondol Stars,ABC Motsepe,Pretoria Callies,Home,Derby,2,0.76,2026,4,9
9,Royal AM,PSL,Bush Bucks,Home,Night Match,2,0.48,2026,4,10

Let us combine all the seperate columns of date into a single Match Date column

In [66]:
# Let us combine all the seperate columns of date into a single Match Date
df['Match Date'] = pd.to_datetime(df[['Year', 'Month', 'Day']])
df

,Team Name,League,Opponent,Location,Match Condition,Goals Last 3,Win Probability,Year,Month,Day,Match Date
0,University of Pretoria,NFD,Bush Bucks,Away,Derby,6,0.86,2026,4,1,2026-04-01
1,Richards Bay,PSL,Baroka FC,Home,Windy,3,0.69,2026,4,2,2026-04-02
2,Magesi FC,NFD,Mangaung United,Away,Windy,6,0.32,2026,4,3,2026-04-03
3,Mpheni Home Defenders,ABC Motsepe,Santos FC,Home,Night Match,4,0.35,2026,4,4,2026-04-04
4,Sekhukhune United,PSL,Baroka FC,Away,Night Match,6,0.71,2026,4,5,2026-04-05
5,Dondol Stars,ABC Motsepe,Casric Stars,Home,Derby,0,0.44,2026,4,6,2026-04-06
6,Upington City,NFD,Sekhukhune United,Home,Windy,4,0.49,2026,4,7,2026-04-07
7,Zizwe United,ABC Motsepe,Santos FC,Away,Rainy,2,0.37,2026,4,8,2026-04-08
8,Dondol Stars,ABC Motsepe,Pretoria Callies,Home,Derby,2,0.76,2026,4,9,2026-04-09
9,Royal AM,PSL,Bush Bucks,Home,Night Match,2,0.48,2026,4,10,2026-04-10